# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
archives_base_name=iron-jetpacks
mod_version=0.4.7
maven_group=com.blakebr0.ironjetpacks

minecraft_version=26.1.2
loader_version=0.19.2
fabric_version=0.147.0+26.1.2

clothconfig_version=26.1.154
rei_version=21.11.814
tr_energy_version=5.0.0